version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 609946765885.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker --version
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Build started on `date`
      - echo Building the Docker image 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno
      - docker build -t 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno:latest .
      - docker tag 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno:latest 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno:latest
      - docker push 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nate-deno","imageUri":"%s"}]' 609946765885.dkr.ecr.us-east-1.amazonaws.com/nate-deno:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json